import Image from "next/image";
import { Layout, PropertyCard, PropertyCardHeroWrapper } from "../components";
import { FaBed, FaBath } from "react-icons/fa";
import { MdLocationPin } from "react-icons/md";
import Link from "next/link";
import { PropertyCardProps } from "../types";

const headOptions = {
  description: "Generated by create next app",
  title: "Create Next App",
};

const propertyCards: PropertyCardProps[] = [
  {
    src: "https://cdn.rareblocks.xyz/collection/clarity-ecommerce/images/hero/2/artwork-1.png",
    alt: "",
    width: 0,
    height: 0,
    title: "Ely-The Angry Girl",
    description:
      "Culpa est occaecat cillum anim duis ut fugiat reprehenderit duis aliqua non ex consequat. Amet ex in Lorem exercitation labore mollit sunt. Mollit duis non officia cupidatat voluptate mollit cupidatat cupidatat nulla consequat elit ut non.Nisi aute culpa exercitation tempor amet enim ex aliquip. Eu occaecat pariatur tempor ea. Incididunt ex amet reprehenderit cupidatat fugiat do esse dolore qui. Eiusmod deserunt sit aliqua exercitation irure ullamco ipsum Lorem duis. Excepteur deserunt occaecat enim in consequat anim nulla ipsum ad. Cupidatat veniam et occaecat incididunt consequat nulla incididunt. Occaecat qui exercitation minim pariatur id ad labore id sit nostrud.",
    price: 9394,
  },
  {
    src: "https://cdn.rareblocks.xyz/collection/clarity-ecommerce/images/hero/2/artwork-2.png",
    alt: "",
    width: 0,
    height: 0,
    title: "EJenny-Retro Art",
    description:
      "Ullamco nulla cillum non duis deserunt sint irure incididunt ad ut velit. Anim consequat amet cupidatat cupidatat duis deserunt esse et adipisicing ad ullamco aute adipisicing do. Consequat et dolor magna ea consequat id aliquip incididunt enim. Id cupidatat labore exercitation incididunt nisi dolore dolore ex dolore. Laborum cillum aute minim fugiat aliqua consequat culpa tempor qui sit reprehenderit commodo proident fugiat. Ullamco enim qui cillum enim deserunt cupidatat amet deserunt. Aute enim magna labore sit eu do nostrud nulla elit est sit exercitation. Qui veniam non laborum incididunt aliquip in in voluptate anim. Nulla esse culpa amet proident irure ullamco. Lorem id laboris cillum proident deserunt proident ipsum commodo labore. Aute irure ipsum pariatur sunt nulla in elit. Nostrud aliquip eiusmod cillum velit veniam. Id voluptate minim fugiat ipsum qui sunt irure reprehenderit est aute.",
    price: 7627,
  },

  {
    src: "https://cdn.rareblocks.xyz/collection/clarity-ecommerce/images/hero/2/artwork-3.png",
    alt: "",
    width: 0,
    height: 0,
    title: "Naila-The Angry Girl",
    description:
      "Reprehenderit esse labore exercitation aliqua elit ipsum quis excepteur magna et. Officia quis sint excepteur laborum eiusmod proident fugiat eiusmod veniam qui. Reprehenderit et sit voluptate ea enim officia sint eu dolor enim. Duis ad est pariatur officia consectetur. Laboris culpa enim magna Lorem adipisicing. Deserunt labore eiusmod magna cupidatat. Dolor laborum non veniam elit esse mollit nulla excepteur occaecat. Consequat ea sit anim dolore voluptate minim commodo. Eiusmod fugiat Lorem commodo irure esse mollit aute elit ut ad eiusmod ad. Officia ut ullamco in sunt in esse sint minim consectetur id qui magna. Qui et et ad tempor nostrud dolor.",
    price: 0,
  },
];

export default function Home() {
  return (
    <Layout headOptions={headOptions}>
      <>
        <div className="relative py-12 overflow-hidden sm:py-16 lg:py-20 xl:py-24">
          <div className="px-4 mx-auto sm:px-6 lg:px-8 max-w-7xl">
            <div className="flex flex-col">
              <div className="max-w-md mx-auto text-center xl:max-w-lg lg:mx-0 lg:text-left">
                <h1 className="text-3xl font-bold text-gray-900 sm:text-4xl md:text-5xl lg:leading-tight xl:text-6xl">
                  Collect rare ✨ digital artworks
                </h1>
                <p className="mt-5 text-lg font-medium text-gray-900 lg:mt-8">
                  Buy & sell NFTs from world’s top artist
                </p>

                <div className="mt-8 lg:mt-10">
                  <a
                    href="#"
                    title=""
                    className="inline-flex items-center justify-center px-8 py-3 text-base font-bold leading-7 text-white transition-all duration-200 bg-gray-900 border border-transparent focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900 font-pj hover:bg-gray-600"
                    role="button"
                  >
                    Explore all properties
                  </a>
                </div>

                <div className="mt-8 lg:mt-12">
                  <svg
                    className="w-auto h-4 mx-auto text-gray-300 lg:mx-0"
                    viewBox="0 0 172 16"
                    fill="none"
                    stroke="currentColor"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 11 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 46 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 81 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 116 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 151 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 18 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 53 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 88 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 123 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 158 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 25 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 60 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 95 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 130 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 165 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 32 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 67 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 102 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 137 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 172 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 39 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 74 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 109 1)"
                    ></line>
                    <line
                      y1="-0.5"
                      x2="18.0278"
                      y2="-0.5"
                      transform="matrix(-0.5547 0.83205 0.83205 0.5547 144 1)"
                    ></line>
                  </svg>
                </div>

                <div className="inline-grid grid-cols-2 mt-8 gap-x-8">
                  <div>
                    <p className="text-4xl font-bold text-gray-900">50k+</p>
                    <p className="mt-2 text-base font-medium text-gray-500">
                      Agents
                    </p>
                  </div>

                  <div>
                    <p className="text-4xl font-bold text-gray-900">17k+</p>
                    <p className="mt-2 text-base font-medium text-gray-500">
                      Homes
                    </p>
                  </div>
                </div>
              </div>

              <PropertyCardHeroWrapper />
            </div>
          </div>
        </div>

        <section className="container px-2 lg:px-4 py-10 mx-auto overflow-hidden ">
          <div className="lg:flex lg:-mx-6 justify-between">
            {/* SideBar */}
            <div className="hidden mt-8 lg:block lg:w-1/4 lg:mt-0 lg:px-6">
              <div>
                <h3 className="text-black capitalize font-semibold">
                  Design instument
                </h3>

                <a
                  href="#"
                  className="block mt-2 font-medium text-gray-700 hover:underline hover:text-gray-500 dark:text-gray-400 "
                >
                  How to raise $100k+ by using blox ui kit on your design
                </a>
              </div>

              <hr className="my-6 border-gray-200 dark:border-gray-700" />

              <div>
                <h3 className="text-black capitalize font-semibold">
                  UI Resource
                </h3>

                <a
                  href="#"
                  className="block mt-2 font-medium text-gray-700 hover:underline hover:text-gray-500 dark:text-gray-400 "
                >
                  Should you creat UI Product by using Blox?
                </a>
              </div>

              <hr className="my-6 border-gray-200 dark:border-gray-700" />

              <div>
                <h3 className="text-black capitalize font-semibold">
                  Premium Collection
                </h3>

                <a
                  href="#"
                  className="block mt-2 font-medium text-gray-700 hover:underline hover:text-gray-500 dark:text-gray-400 "
                >
                  Top 10 Blocks you can get on Blox&apos;s collection.
                </a>
              </div>

              <hr className="my-6 border-gray-200 dark:border-gray-700" />

              <div>
                <h3 className="text-black capitalize font-semibold">
                  Premium kits
                </h3>

                <a
                  href="#"
                  className="block mt-2 font-medium text-gray-700 hover:underline hover:text-gray-500 dark:text-gray-400 "
                >
                  Top 10 Ui kit you can get on Blox&apos;s collection.
                </a>
              </div>
            </div>

            {/* grid */}
            <div className=" px-4 max-w-7xl sm:px-6 lg:px-8 ">
              <div className="max-w-md text-start">
                <h2 className="text-3xl font-bold text-gray-900 sm:text-4xl ">
                  Trending Properties
                </h2>
              </div>

              <div className="grid max-w-3xl grid-cols-1 mx-auto mt-8 sm:mt-16 sm:text-left sm:grid-cols-2 gap-y-4 gap-x-2 lg:gap-x-4">
                {/* items */}
                {propertyCards.map((property, i) => (
                  <PropertyCard key={i} card={property} />
                ))}
                {propertyCards.map((property, i) => (
                  <PropertyCard key={i} card={property} />
                ))}
                {propertyCards.map((property, i) => (
                  <PropertyCard key={i} card={property} />
                ))}
              </div>
            </div>
          </div>
        </section>
      </>
    </Layout>
  );
}
